import type { Metadata } from "next"
import './globals.css'
import { ReactNode } from 'react'
import Header from "@/components/Header"

export const metadata: Metadata = {
  title: 'Your App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}